### ISSUE TITLE
Problem when using pnpm

### ISSUE THREAD

**Issue by lazee** [Siedlerchr/types-ol-ext#133]
Hi,

When bundling an internal package with rollup and pnpm, that are using types-ol-ext, I get this error:

```
[!] (plugin rpt2) Error: error TS6053: File '/Users/jakob/tmp/kraken/frontend/node_modules/.pnpm/@siedlerchr+types-ol-ext@3.2.0/node_modules/@siedlerchr/types-ol-ext/index.d.ts' not found.
  The file is in the program because:
    Entry point for implicit type library 'ol-ext' with packageId '@siedlerchr/types-ol-ext/index.d.ts@3.2.0'
```

We are on Typescript 4.6.4 (maybe that is the problem). 

The problem seems to be that the index.d.ts file i empty in this package. If I add a whitespace to this file, in the above path, then everything works. 

Does anybody know the core issue behind this? If not, would it be possible to add something to the index.d.ts file, so that it is not empty? A comment or something :)

**Comment by Siedlerchr** [comment]
>Does anybody know the core issue behind this? If not, would it be possible to add something to the index.d.ts file, so that it is not empty? A comment or something :)

I have no idea! I am really not that deep into the build system stuff.
Feel free to add a comment or something to the file it helps. 

(Please note that I am on holiday for the next two weeks with limited availability)

**Comment by lazee** [comment]
Ok, I will fix a PR. Have a nice holiday :)

**Comment by aoguoxiang** [comment]
> Hi,
> 
> When bundling an internal package with rollup and pnpm, that are using types-ol-ext, I get this error:
> 
> ```
> [!] (plugin rpt2) Error: error TS6053: File '/Users/jakob/tmp/kraken/frontend/node_modules/.pnpm/@siedlerchr+types-ol-ext@3.2.0/node_modules/@siedlerchr/types-ol-ext/index.d.ts' not found.
>   The file is in the program because:
>     Entry point for implicit type library 'ol-ext' with packageId '@siedlerchr/types-ol-ext/index.d.ts@3.2.0'
> ```
> 
> We are on Typescript 4.6.4 (maybe that is the problem).
> 
> The problem seems to be that the index.d.ts file i empty in this package. If I add a whitespace to this file, in the above path, then everything works.
> 
> Does anybody know the core issue behind this? If not, would it be possible to add something to the index.d.ts file, so that it is not empty? A comment or something :)

not work in typescript@5.0.4. when i `import Splitter from ol-ext/interaction/Splitter`，vscode report

**Comment by aoguoxiang** [comment]
![image](https://github.com/Siedlerchr/types-ol-ext/assets/47943650/d7439e46-4b3d-4fb8-92a2-65376e2a768b)

**Comment by aoguoxiang** [comment]
> Hi,
> 
> When bundling an internal package with rollup and pnpm, that are using types-ol-ext, I get this error:
> 
> ```
> [!] (plugin rpt2) Error: error TS6053: File '/Users/jakob/tmp/kraken/frontend/node_modules/.pnpm/@siedlerchr+types-ol-ext@3.2.0/node_modules/@siedlerchr/types-ol-ext/index.d.ts' not found.
>   The file is in the program because:
>     Entry point for implicit type library 'ol-ext' with packageId '@siedlerchr/types-ol-ext/index.d.ts@3.2.0'
> ```
> 
> We are on Typescript 4.6.4 (maybe that is the problem).
> 
> The problem seems to be that the index.d.ts file i empty in this package. If I add a whitespace to this file, in the above path, then everything works.
> 
> Does anybody know the core issue behind this? If not, would it be possible to add something to the index.d.ts file, so that it is not empty? A comment or something :)

not work in TypeScript@5.0.4, when i `import Splitter from "ol-ext/interaction/Splitter"`, VSCode report type error
![image](https://github.com/Siedlerchr/types-ol-ext/assets/47943650/2b7315b1-84db-464f-b1b4-08782333bb48)

**Comment by Siedlerchr** [comment]
I can take a look the next days

**Comment by Siedlerchr** [comment]
I have created a new release with updated Typescript etc. Mabye you can try again

**Comment by digoburigo** [comment]
version `3.0.1`
working
![image](https://github.com/Siedlerchr/types-ol-ext/assets/28462822/c04fe4ca-655e-4c5a-a08f-6ee1811e2832)

version `3.2.1`
not working
![image](https://github.com/Siedlerchr/types-ol-ext/assets/28462822/eee2c4c0-a5a1-429d-93fb-53910ababa3e)

Apparently the current version creates subfolders and TypeScript cannot identify the types

**Comment by Siedlerchr** [comment]
Maybe this file is the culprit https://github.com/Siedlerchr/types-ol-ext/blob/master/%40types/ol-ext/index.d.ts

**Comment by GoutaamT** [comment]
> Maybe this file is the culprit https://github.com/Siedlerchr/types-ol-ext/blob/master/%40types/ol-ext/index.d.ts

What should be done to rectify this subfolder issue in the latest release?

**Comment by Siedlerchr** [comment]
I don't kow, but mabye deleting this file I linked above helps to recognize it correctly?

**Comment by GoutaamT** [comment]
> I don't kow, but mabye deleting this file I linked above helps to recognize it correctly?

Even after deleting the file, it is not recognizing correctly. Also since we're using an automated build pipeline, any manual modification is not possible.

I think the subfolders (./@types/ol-ext/) need to be removed and the folder structure be like how it was until the previous release, i.e. v-3.2.0.

**Comment by Siedlerchr** [comment]
The folder structure didn't change. it was always like that. You can see the diff here;
https://github.com/Siedlerchr/types-ol-ext/compare/3.2.0...3.2.1

**Comment by GoutaamT** [comment]
> version `3.0.1` / `3.2.0` working ![image](https://user-images.githubusercontent.com/28462822/262785845-6c61f878-cb37-44b5-9342-743eab909a5a.png)
> 
> version `3.2.1` not working ![image](https://user-images.githubusercontent.com/28462822/262784923-eee2c4c0-a5a1-429d-93fb-53910ababa3e.png)
> 
> Apparently the current version creates subfolders and TypeScript cannot identify the types

@Siedlerchr, as pointed out by @digoburigo here, the folder structure now has 2 subfolders

**Comment by Siedlerchr** [comment]
Hm maybe something with the publishing script is not right

**Comment by GoutaamT** [comment]
> Hm maybe something with the publishing script is not right

will it be resolved and a new release created soon?

**Comment by Siedlerchr** [comment]
I can not promise anything. But I will try

**Comment by Siedlerchr** [comment]
As I suspected the issue was indeed the publishing. New release is up. checked the package content. Should be all fine now

**Comment by Siedlerchr** [comment]
If the issue persists or comes up again, just reopen

**Comment by lukastemberga** [comment]
Hi!
It seems this issue is not fixed for npm package version `3.2.3`. I have done some testing and it seems TypeScript requires `index.d.ts` file present in `@types/ol-ext/` otherwise I get an error same as mentioned above. This file seems to be working either empty or with just a comment/whitespace in it (content doesn't matter). Can we add this file back into `@types/ol-ext/` directory?
I think the folder structure itself is good but pretty much every other node module specifies this `index.d.ts` file inside `@types/<package>` as far as I can tell.

**Comment by Siedlerchr** [comment]
Ah okay, it needs to be in the ol-ext subdir as well.
